language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - yarn install
  - yarn testci
after_script:
  - yarn install -g codecov
  - codecov