
language: node_js
node_js:
  - 10.15.1
cache:
  directories:
  - node_modules


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - npm install
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js